### ISSUE TITLE
Add async submission methods

### ISSUE THREAD

**Issue by pc9795** [exceptionless/Exceptionless.Java#27]
Currently, we support methods such as `submitLog` that submit events synchronously. Add corresponding methods to submit this asynchronously.

**Comment by niemyjski** [comment]
In our new JavaScript client we have submit be async (due to library calls that forced us to be async in the plugins) but it doesn't make http requests as that happens in a background job on the queue.. In .NET Event submission is fully synchronous. I don't see any point to add async calls if nothing else is async.

**Comment by niemyjski** [comment]
Reopened just to track last comment on async methods

**Comment by pc9795** [comment]
Actually, you are right as event submission happens through a queue the codebase is already async. The only thing which will be made async through `submitXXXAsync` methods will be the plugin runs. Until these plugins are doing some heavy lifting then there is no sense in having these async methods.

**Comment by pc9795** [comment]
I will add some documentation more importantly in the public-facing classes. https://github.com/exceptionless/Exceptionless.Java/issues/37
